import React, { useState } from "react";
import { FaDownload, FaFilePdf, FaFileExcel } from "react-icons/fa";

const reportData = [
  {
    type: "Case Report",
    date: "23 Jul 2025",
    generatedBy: "Admin",
    filter: "Last 1 Month",
    fileType: "pdf",
    link: "/downloads/case-report.pdf",
  },
  {
    type: "Donation Report",
    date: "01 Jul 2025",
    generatedBy: "Admin",
    filter: "2025 Q2",
    fileType: "excel",
    link: "/downloads/donation-report.xlsx",
  },
];

const DetailedReportsTable = () => {
  const [searchTerm, setSearchTerm] = useState("");

  const filteredReports = reportData.filter((report) =>
    report.type.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-semibold">Detailed Reports</h2>
        <input
          type="text"
          placeholder="Search reports..."
          className="border p-2 rounded-md w-64 focus:outline-none focus:ring-2 focus:ring-blue-400"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full text-left text-sm">
          <thead className="bg-gray-100 text-gray-700">
            <tr>
              <th className="px-4 py-2">Report Type</th>
              <th className="px-4 py-2">Generated On</th>
              <th className="px-4 py-2">Generated By</th>
              <th className="px-4 py-2">Filters Applied</th>
              <th className="px-4 py-2">Download</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.length > 0 ? (
              filteredReports.map((report, index) => (
                <tr
                  key={index}
                  className="border-b hover:bg-gray-50 transition duration-150"
                >
                  <td className="px-4 py-2 flex items-center gap-2">
                    {report.fileType === "pdf" ? (
                      <FaFilePdf className="text-red-500" />
                    ) : (
                      <FaFileExcel className="text-green-500" />
                    )}
                    {report.type}
                  </td>
                  <td className="px-4 py-2">{report.date}</td>
                  <td className="px-4 py-2">{report.generatedBy}</td>
                  <td className="px-4 py-2">{report.filter}</td>
                  <td className="px-4 py-2">
                    <a
                      href={report.link}
                      download
                      className="flex items-center text-blue-600 hover:underline gap-2"
                    >
                      <FaDownload />
                      {report.fileType === "pdf" ? "PDF" : "Excel"}
                    </a>
                  </td>
                </tr>
              ))
            ) : (
              <tr>
                <td
                  colSpan="5"
                  className="text-center text-gray-500 px-4 py-6"
                >
                  No reports found.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default DetailedReportsTable;
